shuffle: roundrobin
deployment_mode: local
config:
  activeEpoch: 18
  keyType: "hash-sig"
validators:
  - name: "nlean_0"
    privkey: "2e9be3f1b0d32ca3a4d62017fbfafe3950b7e90fed6802ff8bd2e0f8c4e2ca91"
    enrFields:
      ip: "127.0.0.1"
      quic: 9101
    metricsPort: 18081
    count: 1

  - name: "nlean_1"
    privkey: "bdf953adc161873ba026330c56450453f582e3c4ee6cb713644794bcfdd85fe5"
    enrFields:
      ip: "127.0.0.1"
      quic: 9102
    metricsPort: 18082
    count: 1

  - name: "ream_0"
    privkey: "af27950128b49cda7e7bc9fcb7b0270f7a3945aa7543326f3bfdbd57d2a97a32"
    enrFields:
      ip: "127.0.0.1"
      quic: 9103
    metricsPort: 18083
    devnet: 2
    count: 1
